# Generated by Django 4.2.16 on 2024-09-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('project_link', models.URLField(unique=True)),
                ('work_experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('certification_name', models.CharField(max_length=255)),
                ('certification_link', models.URLField(unique=True)),
            ],
        ),
    ]
